/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.edu.movieticketreservation.view;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.Optional;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import lk.ijse.edu.movieticketreservation.pnl.ManageMeals;
import lk.ijse.edu.movieticketreservation.pnl.ManageMove;
import lk.ijse.edu.movieticketreservation.pnl.ManageUser;
import lk.ijse.edu.movieticketreservation.pnl.Shadule;
import lk.ijse.edu.movieticketreservation.pnl.ShowMoving;
import lk.ijse.edu.movieticketreservation.pnl.ViewReports;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author sachin dilshan
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    
String title = "Sihina Cinema .";
 String subString = "";
    public DashBoard() {
        initComponents();
        noveDate();
        homePage();
        nowTime();
        runLabel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblManage = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lblMeals = new javax.swing.JLabel();
        lblReport = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblShadule = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        homePnl = new javax.swing.JPanel();

        jLabel22.setText("jLabel22");

        jLabel25.setText("jLabel25");

        jLabel27.setText("jLabel27");

        jToolBar1.setRollover(true);

        jLabel7.setText("     LogOut");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDate.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 0, 51));
        lblDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 190, 40));

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 255, 255));
        jLabel24.setText("Sihina Cinema . ");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 40));

        lblTime.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 0, 51));
        jPanel3.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 250, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 40));

        jPanel4.setBackground(new java.awt.Color(1, 50, 67));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Video_Camera_50px.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Add_User_Group_Man_Man_50px.png"))); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, 46));

        lblUser.setBackground(new java.awt.Color(1, 50, 67));
        lblUser.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 204, 255));
        lblUser.setText("     Manage User");
        lblUser.setOpaque(true);
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUserMouseExited(evt);
            }
        });
        jPanel4.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 180, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Food_And_Wine_50px_1.png"))); // NOI18N
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, 47));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Magazine_50px_2.png"))); // NOI18N
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 50, 46));

        jLabel21.setBackground(new java.awt.Color(82, 179, 217));
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabel21.setOpaque(true);
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 6, 40));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Logout_Rounded_Up_50px.png"))); // NOI18N
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 50, 46));

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setOpaque(true);
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 250, 29));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Home_50px.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 50, 50));

        lblHome.setBackground(new java.awt.Color(1, 50, 67));
        lblHome.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 204, 255));
        lblHome.setText("       Home");
        lblHome.setOpaque(true);
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
        });
        jPanel4.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 180, 40));

        lblManage.setBackground(new java.awt.Color(1, 50, 67));
        lblManage.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        lblManage.setForeground(new java.awt.Color(255, 204, 255));
        lblManage.setText("      Manage Movies");
        lblManage.setOpaque(true);
        lblManage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblManageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblManageMouseExited(evt);
            }
        });
        jPanel4.add(lblManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 180, 40));

        jLabel28.setBackground(new java.awt.Color(82, 179, 217));
        jLabel28.setOpaque(true);
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 6, 40));

        jLabel29.setBackground(new java.awt.Color(82, 179, 217));
        jLabel29.setOpaque(true);
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 6, 40));

        jLabel31.setBackground(new java.awt.Color(82, 179, 217));
        jLabel31.setOpaque(true);
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 6, 40));

        lblMeals.setBackground(new java.awt.Color(1, 50, 67));
        lblMeals.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        lblMeals.setForeground(new java.awt.Color(255, 204, 255));
        lblMeals.setText("     Manage Meals");
        lblMeals.setOpaque(true);
        lblMeals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMealsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMealsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMealsMouseExited(evt);
            }
        });
        jPanel4.add(lblMeals, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 180, 40));

        lblReport.setBackground(new java.awt.Color(1, 50, 67));
        lblReport.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        lblReport.setForeground(new java.awt.Color(255, 204, 255));
        lblReport.setText("    View Report");
        lblReport.setOpaque(true);
        lblReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReportMouseExited(evt);
            }
        });
        jPanel4.add(lblReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 180, 40));

        jLabel9.setBackground(new java.awt.Color(1, 50, 67));
        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 255));
        jLabel9.setText("     LogOut");
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 180, 40));

        lblShadule.setBackground(new java.awt.Color(1, 50, 67));
        lblShadule.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        lblShadule.setForeground(new java.awt.Color(255, 204, 255));
        lblShadule.setText("    Manage Shadule");
        lblShadule.setOpaque(true);
        lblShadule.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblShaduleAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        lblShadule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShaduleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblShaduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblShaduleMouseExited(evt);
            }
        });
        jPanel4.add(lblShadule, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 180, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Calendar_50px.png"))); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 50, 40));

        jLabel30.setBackground(new java.awt.Color(82, 179, 217));
        jLabel30.setOpaque(true);
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 6, 40));

        jLabel32.setBackground(new java.awt.Color(82, 179, 217));
        jLabel32.setOpaque(true);
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 6, 40));

        jLabel33.setBackground(new java.awt.Color(82, 179, 217));
        jLabel33.setOpaque(true);
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 6, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 260, 740));

        homePnl.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout homePnlLayout = new javax.swing.GroupLayout(homePnl);
        homePnl.setLayout(homePnlLayout);
        homePnlLayout.setHorizontalGroup(
            homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        homePnlLayout.setVerticalGroup(
            homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jPanel2.add(homePnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 1120, 700));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblManageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageMouseClicked
        ManageMove move = new ManageMove();
        homePnl.removeAll();
        move.setSize(homePnl.getSize());
        homePnl.add(move);
        homePnl.revalidate();
        homePnl.repaint();
    }//GEN-LAST:event_lblManageMouseClicked

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        setColuers();
        lblHome.setBackground(new Color(1, 152, 117));
        ShowMoving move = new ShowMoving();
        homePnl.removeAll();
        move.setSize(homePnl.getSize());
        homePnl.add(move);
        homePnl.revalidate();
        homePnl.repaint();
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        lblHome.setBackground(new Color(1, 152, 117));

    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblManageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageMouseEntered
        lblManage.setBackground(new Color(1, 152, 117));

    }//GEN-LAST:event_lblManageMouseEntered

    private void lblManageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageMouseExited
        lblManage.setBackground(new Color(1, 50, 67));
    }//GEN-LAST:event_lblManageMouseExited

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        lblHome.setBackground(new Color(1, 50, 67));
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseEntered
        lblUser.setBackground(new Color(1, 152, 117));

    }//GEN-LAST:event_lblUserMouseEntered

    private void lblUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseExited
        lblUser.setBackground(new Color(1, 50, 67));
    }//GEN-LAST:event_lblUserMouseExited

    private void lblMealsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMealsMouseEntered
        lblMeals.setBackground(new Color(1, 152, 117));

    }//GEN-LAST:event_lblMealsMouseEntered

    private void lblMealsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMealsMouseExited
        lblMeals.setBackground(new Color(1, 50, 67));
    }//GEN-LAST:event_lblMealsMouseExited

    private void lblReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseEntered
        lblReport.setBackground(new Color(1, 152, 117));

    }//GEN-LAST:event_lblReportMouseEntered
    private void setColuers() {
        lblHome.setBackground(new Color(1, 50, 67));
        lblManage.setBackground(new Color(1, 50, 67));
        lblUser.setBackground(new Color(1, 50, 67));
        lblMeals.setBackground(new Color(1, 50, 67));
        lblReport.setBackground(new Color(1, 50, 67));
        lblShadule.setBackground(new Color(1, 50, 67));

    }
    private void lblReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseExited
        lblReport.setBackground(new Color(1, 50, 67));
    }//GEN-LAST:event_lblReportMouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        jLabel9.setBackground(new Color(1, 152, 117));
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        jLabel9.setBackground(new Color(1, 50, 67));
    }//GEN-LAST:event_jLabel9MouseExited

    private void lblMealsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMealsMouseClicked
        ManageMeals mels = new ManageMeals();
        homePnl.removeAll();
        mels.setSize(homePnl.getSize());
        homePnl.add(mels);
        homePnl.revalidate();
        homePnl.repaint();
    }//GEN-LAST:event_lblMealsMouseClicked

    private void lblReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseClicked
        ViewReports report = new ViewReports();
        homePnl.removeAll();
        report.setSize(homePnl.getSize());
        homePnl.add(report);
        homePnl.revalidate();
        homePnl.repaint();
    }//GEN-LAST:event_lblReportMouseClicked

    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
        ManageUser user = new ManageUser();
        homePnl.removeAll();
        user.setSize(homePnl.getSize());
        homePnl.add(user);
        homePnl.revalidate();
        homePnl.repaint();

    }//GEN-LAST:event_lblUserMouseClicked

    private void lblShaduleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShaduleMouseEntered
        lblShadule.setBackground(new Color(1, 152, 117));
    }//GEN-LAST:event_lblShaduleMouseEntered

    private void lblShaduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShaduleMouseExited
        lblShadule.setBackground(new Color(1, 50, 67));
    }//GEN-LAST:event_lblShaduleMouseExited

    private void lblShaduleAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblShaduleAncestorAdded

    }//GEN-LAST:event_lblShaduleAncestorAdded

    private void lblShaduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShaduleMouseClicked
        Shadule shedul = new Shadule();
        homePnl.removeAll();
        shedul.setSize(homePnl.getSize());
        homePnl.add(shedul);
        homePnl.revalidate();
        homePnl.repaint();
    }//GEN-LAST:event_lblShaduleMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
         this.dispose();
                Login login=new Login();
                login.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    //   UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel homePnl;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblManage;
    private javax.swing.JLabel lblMeals;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblShadule;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables

    private void noveDate() {
        lblDate.setText(LocalDate.now().toString());
    }

    private void homePage() {
        ShowMoving move = new ShowMoving();
        homePnl.removeAll();
        move.setSize(homePnl.getSize());
        homePnl.add(move);
        homePnl.revalidate();
        homePnl.repaint();
    }

    private void nowTime() {
        new Thread(() -> {
            while (true) {
                Date date = new Date();
                String currentdate = new SimpleDateFormat("hh:mm:ss aa").format(date);

                lblTime.setText(currentdate);
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {

                }
            }
        }).start();
    }

    private void runLabel() {

        
        setFont(new Font("Areal", 3, 12));
        setTitle(" \" Sihina Cinema .    \'1.5 VERSION\' \"");
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        new Thread() {
            public void run() {
                for (int i = 0; i < title.length() + 1; i++) {
                    try {
                        if (i == title.length()) {
                            i = 0;
                            subString = "";
                        }
                        subString += title.substring(i, i + 1);
                        jLabel24.setText(subString);
                        sleep(500);
                    } catch (InterruptedException ex) {
                        JOptionPane.showMessageDialog(DashBoard.this, "Database Error...");
                    }
                }
            }
        }.start();

    }
}
