/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.edu.movieticketreservation.pnl;

import java.awt.Color;
import static java.awt.Color.red;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.scripts.JO;
import lk.ijse.edu.movieticketreservation.controller.ManageCategoryController;
import lk.ijse.edu.movieticketreservation.controller.ManageShaduleController;
import lk.ijse.edu.movieticketreservation.controller.SeateTypeController;
import lk.ijse.edu.movieticketreservation.entity.Shedule;
import lk.ijse.edu.movieticketreservation.mdel.CategortDTO;
import lk.ijse.edu.movieticketreservation.mdel.SeataTypeDTO;
import lk.ijse.edu.movieticketreservation.mdel.SheduleDTO;

/**
 *
 * @author sachin dilshan
 */
public class Shadule extends javax.swing.JPanel {

    /**
     *
     */
    public Shadule() {
        initComponents();
        loodAllSeatType();
        loodAllCategoryId();
        loodAllsheduleId();
        loodCategoryDetails();
        loodAllSeatTypeDetails();
        loodAllSheduleeDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlShedule = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        comboSheduleId = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtMovieIdS = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        comboCategory = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboSeatType = new javax.swing.JComboBox<>();
        txtPrice = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSeatName = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShedule = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCategory = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSeatType = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        updateVoice = new javax.swing.JLabel();
        updateCategoryVoice = new javax.swing.JLabel();
        updateSeatTypeVoice = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlShedule.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Shedule ID :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 47, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Time           :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 157, 85, -1));

        txtTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTime.setText(" ");
        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });
        jPanel2.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 151, 160, 30));

        comboSheduleId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboSheduleId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(225,225,225), new java.awt.Color(225,225,225), new java.awt.Color(225,225,225), new java.awt.Color(225,225,225)));
        comboSheduleId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboSheduleIdItemStateChanged(evt);
            }
        });
        comboSheduleId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSheduleIdActionPerformed(evt);
            }
        });
        jPanel2.add(comboSheduleId, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 36, 160, 39));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Movie ID    :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 107, 85, -1));

        txtMovieIdS.setEditable(false);
        txtMovieIdS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMovieIdS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovieIdSActionPerformed(evt);
            }
        });
        jPanel2.add(txtMovieIdS, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 100, 160, 31));

        jButton1.setBackground(new java.awt.Color(46, 204, 113));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Software_Installer_20px.png"))); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 199, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Category Id :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 45, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Categroy      :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 122, -1, -1));

        txtCategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryActionPerformed(evt);
            }
        });
        jPanel3.add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 116, 153, 30));

        comboCategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboCategory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(225,225,225), new java.awt.Color(225,225,225), new java.awt.Color(225,225,225), new java.awt.Color(225,225,225)));
        comboCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCategoryItemStateChanged(evt);
            }
        });
        jPanel3.add(comboCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 34, 153, 38));

        jButton2.setBackground(new java.awt.Color(46, 204, 113));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Software_Installer_20px.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 199, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Shedule Details");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Category Details");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Seat typ      :");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 46, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Price             :");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 90, -1, -1));

        comboSeatType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboSeatType.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(225,225,225), new java.awt.Color(225,225,225), new java.awt.Color(225,225,225), new java.awt.Color(225,225,225)));
        comboSeatType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboSeatTypeItemStateChanged(evt);
            }
        });
        comboSeatType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeatTypeActionPerformed(evt);
            }
        });
        jPanel4.add(comboSeatType, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 36, 142, 36));

        txtPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        jPanel4.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 90, 105, 29));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Saet Name  :");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 143, -1, -1));

        txtSeatName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSeatName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatNameActionPerformed(evt);
            }
        });
        jPanel4.add(txtSeatName, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 137, 153, 30));

        jButton3.setBackground(new java.awt.Color(46, 204, 113));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Software_Installer_20px.png"))); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 199, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Seat Type Details");

        tblShedule.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblShedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Shedule ID", "Shedule"
            }
        ));
        tblShedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSheduleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblShedule);

        tblCategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category ID", "Category"
            }
        ));
        tblCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCategory);

        tblSeatType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblSeatType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seat Type", "Seat Price"
            }
        ));
        tblSeatType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSeatTypeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSeatType);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Data_Sheet_100px_1.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Timer_100px_1.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Engravers MT", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Manage Details");

        updateVoice.setText(" Update shedule successfully");

        updateCategoryVoice.setText("update Category successfully");

        updateSeatTypeVoice.setText("update Seat Type successfully");

        jToggleButton1.setBackground(new java.awt.Color(46, 204, 113));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton1.setText("Next");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSheduleLayout = new javax.swing.GroupLayout(pnlShedule);
        pnlShedule.setLayout(pnlSheduleLayout);
        pnlSheduleLayout.setHorizontalGroup(
            pnlSheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSheduleLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addGroup(pnlSheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSheduleLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(updateCategoryVoice, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11))
                    .addGroup(pnlSheduleLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(updateVoice, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(pnlSheduleLayout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlSheduleLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlSheduleLayout.createSequentialGroup()
                .addGap(970, 970, 970)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlSheduleLayout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(updateSeatTypeVoice, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlSheduleLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(pnlSheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSheduleLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSheduleLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnlSheduleLayout.setVerticalGroup(
            pnlSheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSheduleLayout.createSequentialGroup()
                .addGroup(pnlSheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSheduleLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlSheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSheduleLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(updateCategoryVoice))
                            .addGroup(pnlSheduleLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlSheduleLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(updateVoice))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlSheduleLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(updateSeatTypeVoice)))
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(pnlSheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addComponent(jLabel12))
                .addGap(8, 8, 8)
                .addGroup(pnlSheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pnlSheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(pnlShedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 1340, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void comboSeatTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeatTypeActionPerformed
        txtPrice.requestFocusInWindow();
    }//GEN-LAST:event_comboSeatTypeActionPerformed

    private void comboSeatTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboSeatTypeItemStateChanged
        try {
            String seatId = (String) comboSeatType.getSelectedItem();
            SeataTypeDTO setType = SeateTypeController.serchSetSeatType(seatId);
            if (setType != null) {
                txtPrice.setText("" + setType.getSeatPrice());
                txtSeatName.setText(setType.getSatName());
            }
        } catch (Exception ex) {
            Logger.getLogger(Shadule.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_comboSeatTypeItemStateChanged

    private void comboCategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCategoryItemStateChanged
        try {
            String categoryId = (String) comboCategory.getSelectedItem();
            CategortDTO category = ManageCategoryController.serchCategory(categoryId);
            if (category != null) {
                txtCategory.setText(category.getCategoryName());
            }
        } catch (Exception ex) {
            Logger.getLogger(Shadule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboCategoryItemStateChanged

    private void txtCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryActionPerformed
        try {
            String categoryId = (String) comboCategory.getSelectedItem();
            CategortDTO categort = new CategortDTO(categoryId, txtCategory.getText());
            boolean isUpdateed = ManageCategoryController.updateCategory(categort);
            if (isUpdateed) {
                JOptionPane.showMessageDialog(null, "Is update successfully");
                loodCategory();
            } else {
                JOptionPane.showMessageDialog(null, "Con't Update..");
            }
        } catch (Exception ex) {
            Logger.getLogger(Shadule.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        txtSeatName.requestFocusInWindow();

    }//GEN-LAST:event_txtCategoryActionPerformed

    private void txtMovieIdSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMovieIdSActionPerformed
        txtTime.requestFocusInWindow();

    }//GEN-LAST:event_txtMovieIdSActionPerformed
//update Category successfully
    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        try {
            String id = (String) comboSheduleId.getSelectedItem();
            SheduleDTO shedule = new SheduleDTO(id, txtMovieIdS.getText(), txtTime.getText());
            boolean isUpdated = ManageShaduleController.updateCategory(shedule);
            if (isUpdated) {
                JOptionPane.showMessageDialog(null, "Is Update successfully");
                LoodTable();
            } else {

                JOptionPane.showMessageDialog(null, "Con't Update..");
            }
        } catch (Exception ex) {
            Logger.getLogger(Shadule.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        txtCategory.requestFocusInWindow();
    }//GEN-LAST:event_txtTimeActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed


    }//GEN-LAST:event_txtPriceActionPerformed
    private static final String VOICENAME = "kevin16";
    private void txtSeatNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeatNameActionPerformed
        try {
            String seatId = (String) comboSeatType.getSelectedItem();
            double price = Double.parseDouble(txtPrice.getText());
            SeataTypeDTO seataType = new SeataTypeDTO(seatId, price, txtSeatName.getText());
            boolean isUpdated = SeateTypeController.updateSeatType(seataType);
            if (isUpdated) {
                JOptionPane.showMessageDialog(null, "Is Update successfully");
                loodAllSeatTypeDetails();
            } else {

                JOptionPane.showMessageDialog(null, "Con't Update..");
            }
        } catch (Exception ex) {
            Logger.getLogger(Shadule.class.getName()).log(Level.SEVERE, null, ex);
        }
       

    }//GEN-LAST:event_txtSeatNameActionPerformed

    private void comboSheduleIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSheduleIdActionPerformed
        txtMovieIdS.requestFocusInWindow();
    }//GEN-LAST:event_comboSheduleIdActionPerformed

    private void comboSheduleIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboSheduleIdItemStateChanged
        try {
            String sheduleId = (String) comboSheduleId.getSelectedItem();
            SheduleDTO shedule = ManageShaduleController.getTime(sheduleId);
            if (sheduleId != null) {
                txtTime.setText(shedule.getSheduleID());
                txtMovieIdS.setText(shedule.getTime());
            }
        } catch (Exception ex) {
            Logger.getLogger(Shadule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboSheduleIdItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String id = (String) comboSheduleId.getSelectedItem();
            SheduleDTO shedule = new SheduleDTO(id, txtMovieIdS.getText(), txtTime.getText());
            boolean isUpdated = ManageShaduleController.updateCategory(shedule);
            if (isUpdated) {
                JOptionPane.showMessageDialog(null, "Is Update successfully");
                LoodTable();
               
            } else {

                JOptionPane.showMessageDialog(null, "Con't Update..");
            }
        } catch (Exception ex) {
            Logger.getLogger(Shadule.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String categoryId = (String) comboCategory.getSelectedItem();
            CategortDTO categort = new CategortDTO(categoryId, txtCategory.getText());
            boolean isUpdateed = ManageCategoryController.updateCategory(categort);
            if (isUpdateed) {
                JOptionPane.showMessageDialog(null, "Is update successfully");
                loodCategory();
                
            } else {
                JOptionPane.showMessageDialog(null, "Con't Update..");
            }
        } catch (Exception ex) {
            Logger.getLogger(Shadule.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String seatId = (String) comboSeatType.getSelectedItem();
            double price = Double.parseDouble(txtPrice.getText());
            SeataTypeDTO seataType = new SeataTypeDTO(seatId, price, txtSeatName.getText());
            boolean isUpdated = SeateTypeController.updateSeatType(seataType);
            if (isUpdated) {
                JOptionPane.showMessageDialog(null, "Is Update successfully");
                loodAllSeatTypeDetails();
                
            } else {

                JOptionPane.showMessageDialog(null, "Con't Update..");
            }
        } catch (Exception ex) {
            Logger.getLogger(Shadule.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblSheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSheduleMouseClicked
        tblShedule.setDefaultEditor(Object.class, null);
    }//GEN-LAST:event_tblSheduleMouseClicked

    private void tblCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoryMouseClicked
        tblCategory.setDefaultEditor(Object.class, null);
    }//GEN-LAST:event_tblCategoryMouseClicked

    private void tblSeatTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSeatTypeMouseClicked
        tblSeatType.setDefaultEditor(Object.class, null);
    }//GEN-LAST:event_tblSeatTypeMouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        SheduleLoadPnl move = new SheduleLoadPnl();
        pnlShedule.removeAll();
        move.setSize(pnlShedule.getSize());
        pnlShedule.add(move);
        pnlShedule.revalidate();
        pnlShedule.repaint();
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    private void LoodTable() {
        try {
            ArrayList<SheduleDTO> loodCategory = ManageShaduleController.viewSheduleDetails();
            DefaultTableModel dtm = (DefaultTableModel) tblShedule.getModel();
            dtm.setRowCount(0);
            for (SheduleDTO shedule : loodCategory) {
                Object[] rowData = {shedule.getMovieID(), shedule.getTime()};
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(Shadule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loodCategory() {
        try {
            ArrayList<CategortDTO> loodCategory = ManageCategoryController.viewCategoryDetails();
            DefaultTableModel dtm = (DefaultTableModel) tblCategory.getModel();
            dtm.setRowCount(0);
            for (CategortDTO category : loodCategory) {
                Object[] rowData = {category.getCategoryID(), category.getCategoryName()};
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(Shadule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboCategory;
    private javax.swing.JComboBox<String> comboSeatType;
    private javax.swing.JComboBox<String> comboSheduleId;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel pnlShedule;
    private javax.swing.JTable tblCategory;
    private javax.swing.JTable tblSeatType;
    private javax.swing.JTable tblShedule;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtMovieIdS;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSeatName;
    private javax.swing.JTextField txtTime;
    private javax.swing.JLabel updateCategoryVoice;
    private javax.swing.JLabel updateSeatTypeVoice;
    private javax.swing.JLabel updateVoice;
    // End of variables declaration//GEN-END:variables

    private void loodAllSeatType() {
        try {
            ArrayList<String> allSeatType = SeateTypeController.getAllSeatType();
            for (String seat : allSeatType) {
                comboSeatType.addItem(seat);
            }
        } catch (Exception ex) {
            Logger.getLogger(Shadule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loodAllCategoryId() {
        try {
            ArrayList<String> allCategoryId = ManageCategoryController.getAllCategortIds();
            for (String categoryId : allCategoryId) {
                comboCategory.addItem(categoryId);
            }
        } catch (Exception ex) {
            Logger.getLogger(Shadule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loodAllsheduleId() {
        try {
            ArrayList<String> allSheduleId = ManageShaduleController.getAllSheduleId();
            for (String sheduleId : allSheduleId) {
                comboSheduleId.addItem(sheduleId);
            }
        } catch (Exception ex) {
            Logger.getLogger(Shadule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loodCategoryDetails() {
        try {
            ArrayList<CategortDTO> loodCategory = ManageCategoryController.viewCategoryDetails();
            DefaultTableModel dtm = (DefaultTableModel) tblCategory.getModel();
            for (CategortDTO category : loodCategory) {
                Object[] rowData = {category.getCategoryID(), category.getCategoryName()};
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(Shadule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loodAllSeatTypeDetails() {
        try {
            ArrayList<SeataTypeDTO> allSeatType = SeateTypeController.viewSeatTypeDetatis();
            DefaultTableModel dtm = (DefaultTableModel) tblSeatType.getModel();
            dtm.setRowCount(0);
            for (SeataTypeDTO seataType : allSeatType) {
                Object[] row = {seataType.getSeatPrice(), seataType.getSatName()};
                dtm.addRow(row);
            }
        } catch (Exception ex) {
            Logger.getLogger(Shadule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loodAllSheduleeDetails() {
        try {
            ArrayList<SheduleDTO> loodCategory = ManageShaduleController.viewSheduleDetails();
            DefaultTableModel dtm = (DefaultTableModel) tblShedule.getModel();
            for (SheduleDTO shedule : loodCategory) {
                Object[] rowData = {shedule.getMovieID(), shedule.getTime()};
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(Shadule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
