/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.edu.movieticketreservation.pnl;


import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import lk.ijse.edu.movieticketreservation.controller.ManageCategoryController;
import lk.ijse.edu.movieticketreservation.controller.ManageMealController;
import lk.ijse.edu.movieticketreservation.controller.ManageSeatController;
import lk.ijse.edu.movieticketreservation.controller.ManageShaduleController;
import lk.ijse.edu.movieticketreservation.mdel.CategortDTO;
import lk.ijse.edu.movieticketreservation.mdel.SheduleDTO;
import lk.ijse.edu.movieticketresevation.Generator.IDGenerator;

/**
 *
 * @author sachin dilshan
 */
public class SheduleLoadPnl extends javax.swing.JPanel {

    /**
     * Creates new form SheduleLoadPnl
     */
    public SheduleLoadPnl() {
        initComponents();
        GeneratoeMovieID();
        GeneratoeSheduleID();
        loodAllShedule();
        loodAllCatoegory();
        
        tblShedule.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {

                    if (tblShedule.getSelectedRow() == -1) {
                        return;
                    }
                    txtsheduleID.setText((String) tblShedule.getValueAt(tblShedule.getSelectedRow(), 0));
                    txtMovie.setText((String) tblShedule.getValueAt(tblShedule.getSelectedRow(), 1));
                    txtTme.setText((String) tblShedule.getValueAt(tblShedule.getSelectedRow(), 2));
//                    
                }
            });
        
        tblCategory.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {

                if (tblCategory.getSelectedRow() == -1) {
                    return;
                }
                txtCategoryID.setText((String) tblCategory.getValueAt(tblCategory.getSelectedRow(), 0));
                txtCategory.setText((String) tblCategory.getValueAt(tblCategory.getSelectedRow(), 1));
            ;

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTme = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtMovie = new javax.swing.JTextField();
        txtsheduleID = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShedule = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtCategoryID = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCategory = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 51));
        jLabel2.setText("Manage Shedule");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Shedule ID :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 47, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Time           :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 157, 85, -1));

        txtTme.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTme.setText(" ");
        txtTme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTmeActionPerformed(evt);
            }
        });
        jPanel2.add(txtTme, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 151, 160, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Movie ID    :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 107, 85, -1));

        txtMovie.setEditable(false);
        txtMovie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovieActionPerformed(evt);
            }
        });
        jPanel2.add(txtMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 100, 160, 31));

        txtsheduleID.setEditable(false);
        txtsheduleID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtsheduleID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 160, 30));

        jButton2.setBackground(new java.awt.Color(46, 204, 113));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Software_Installer_20px.png"))); // NOI18N
        jButton2.setText("Delect");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jButton1.setBackground(new java.awt.Color(46, 204, 113));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Software_Installer_20px.png"))); // NOI18N
        jButton1.setText(" Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 100, -1));

        tblShedule.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblShedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Shedule ID", "Shedule", "Time"
            }
        ));
        tblShedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSheduleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblShedule);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Category Id :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 45, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Categroy      :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 122, -1, -1));

        txtCategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryActionPerformed(evt);
            }
        });
        jPanel3.add(txtCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 116, 153, 30));

        jButton3.setBackground(new java.awt.Color(46, 204, 113));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Software_Installer_20px.png"))); // NOI18N
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 90, -1));
        jPanel3.add(txtCategoryID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 150, 30));

        jButton4.setBackground(new java.awt.Color(46, 204, 113));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Software_Installer_20px.png"))); // NOI18N
        jButton4.setText("Delect");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 51));
        jLabel3.setText("Manage Category");

        tblCategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category ID", "Category"
            }
        ));
        tblCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCategory);

        jLabel19.setFont(new java.awt.Font("Engravers MT", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Manage Details");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Data_Sheet_100px_1.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Timer_100px_1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(279, 279, 279)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTmeActionPerformed

    }//GEN-LAST:event_txtTmeActionPerformed

    private void txtMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMovieActionPerformed
        txtTme.requestFocusInWindow();
    }//GEN-LAST:event_txtMovieActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String sheduleID = txtsheduleID.getText();
            String movieID = txtMovie.getText();
            String time = txtTme.getText();
            SheduleDTO shedule = new SheduleDTO(sheduleID, movieID, time);
            boolean isAdded = ManageShaduleController.addShedule(shedule);
        } catch (Exception ex) {
            Logger.getLogger(SheduleLoadPnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblSheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSheduleMouseClicked
        tblShedule.setDefaultEditor(Object.class, null);
    }//GEN-LAST:event_tblSheduleMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            if (tblShedule.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "Select a row");
                return;
            }
            boolean result = ManageShaduleController.deleteMeal(tblShedule.getValueAt(tblShedule.getSelectedRow(), 0).toString());
            if (result) {
                JOptionPane.showMessageDialog(this, "Meail has been deleted successfully");
                txtsheduleID.setText("");
                txtMovie.setText("");
                txtTme.setText("");
                loodAllShedule();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete the Meail");
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageMeals.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryActionPerformed

    }//GEN-LAST:event_txtCategoryActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String textid = txtCategoryID.getText();
            String textnname = txtCategory.getText();
            CategortDTO categortDTO = new CategortDTO(textid, textnname);
            boolean iSAdded = ManageCategoryController.addCaegory(categortDTO);
        } catch (Exception ex) {
            Logger.getLogger(SheduleLoadPnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoryMouseClicked
        tblCategory.setDefaultEditor(Object.class, null);
    }//GEN-LAST:event_tblCategoryMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {

            if (tblCategory.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "Select a row");
                return;
            }
            boolean result = ManageCategoryController.deleteCategory(tblCategory.getValueAt(tblCategory.getSelectedRow(), 0).toString());
            if (result) {
                JOptionPane.showMessageDialog(this, "Category has been deleted successfully");
                txtCategoryID.setText("");
                txtCategory.setText("");
                loodAllCatoegory();

            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete the Meail");
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageMeals.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    private void GeneratoeSheduleID() {
        try {
            String shedule;
            shedule = IDGenerator.getNewID("shedule", "SheduleID", "SHID");
            txtsheduleID.setText(shedule);

        } catch (SQLException ex) {
            Logger.getLogger(BookingSeet.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BookingSeet.class
                    .getName()).log(Level.SEVERE, null, ex);

        }
    }

    private void GeneratoeMovieID() {
        try {
            String movie;
            movie = IDGenerator.getNewID("Move", "MovieID", "MVID");
            txtMovie.setText(movie);

        } catch (SQLException ex) {
            Logger.getLogger(BookingSeet.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BookingSeet.class
                    .getName()).log(Level.SEVERE, null, ex);

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCategory;
    private javax.swing.JTable tblShedule;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtCategoryID;
    private javax.swing.JTextField txtMovie;
    private javax.swing.JTextField txtTme;
    private javax.swing.JTextField txtsheduleID;
    // End of variables declaration//GEN-END:variables

    private void loodAllShedule() {
        try {
            ArrayList<SheduleDTO> allMeal = ManageShaduleController.getAllShedule();
            DefaultTableModel dtm = (DefaultTableModel) tblShedule.getModel();
            for (SheduleDTO sheduleDTO : allMeal) {
                Object[] rowDate = {
                    sheduleDTO.getSheduleID(),
                    sheduleDTO.getMovieID(),
                    sheduleDTO.getTime()
                };
                dtm.addRow(rowDate);

            }
        } catch (Exception ex) {
            Logger.getLogger(SheduleLoadPnl.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loodAllCatoegory() {
        try {
            ArrayList<CategortDTO> allCategory = ManageCategoryController.viewCategoryDetails();
            DefaultTableModel dtm = (DefaultTableModel) tblCategory.getModel();
            for (CategortDTO categortDTO : allCategory) {
                Object[] rowData = {
                    categortDTO.getCategoryID(),
                    categortDTO.getCategoryName()
                };
                dtm.addRow(rowData);
            }

        } catch (Exception ex) {
            Logger.getLogger(SheduleLoadPnl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
