/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.edu.movieticketreservation.pnl;

import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.ijse.edu.movieticketreservation.controller.ManageCategoryController;
import lk.ijse.edu.movieticketreservation.controller.ManageCustomerController;
import lk.ijse.edu.movieticketreservation.controller.ManageMovieController;
import lk.ijse.edu.movieticketreservation.controller.ManagePaymentController;
import lk.ijse.edu.movieticketreservation.controller.ManageShaduleController;
import lk.ijse.edu.movieticketreservation.mdel.CategortDTO;
import lk.ijse.edu.movieticketreservation.mdel.CustomerDTO;
import lk.ijse.edu.movieticketreservation.mdel.MovieDTO;
import lk.ijse.edu.movieticketreservation.mdel.PaymentDTO;
import lk.ijse.edu.movieticketreservation.mdel.SheduleDTO;

/**
 *
 * @author sachin dilshan
 */
public class ShowMoving extends javax.swing.JPanel {

    private double sumpayment;

    /**
     * Creates new form ShowMoving
     */
    public ShowMoving() {
        initComponents();
        loodAllpayment();
        loodAlCustomerCount();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRemove = new javax.swing.JPanel();
        pnlDetails = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMovie = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ldbTime1 = new javax.swing.JLabel();
        lblTime2 = new javax.swing.JLabel();
        lblTime3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblAllCustomer = new javax.swing.JLabel();
        allPaymrent1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        pnlRemove.setBackground(new java.awt.Color(255, 255, 255));
        pnlRemove.setForeground(new java.awt.Color(102, 0, 0));

        pnlDetails.setBackground(new java.awt.Color(102, 204, 0));

        javax.swing.GroupLayout pnlDetailsLayout = new javax.swing.GroupLayout(pnlDetails);
        pnlDetails.setLayout(pnlDetailsLayout);
        pnlDetailsLayout.setHorizontalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlDetailsLayout.setVerticalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tableMovie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        tableMovie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableMovie.setForeground(new java.awt.Color(51, 0, 0));
        tableMovie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Show Time", "Movie ID", "Movie Name", "Category", "Start Date", "Closing Date"
            }
        ));
        tableMovie.setAlignmentX(0.9F);
        tableMovie.setAlignmentY(0.9F);
        tableMovie.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        tableMovie.setOpaque(false);
        tableMovie.setRowHeight(20);
        tableMovie.setSelectionBackground(new java.awt.Color(153, 153, 255));
        tableMovie.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tableMovie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMovieMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMovie);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Engravers MT", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Now Showing Movie");
        jLabel6.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("    Show Times");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0), null, new java.awt.Color(153, 0, 0)));
        jLabel1.setOpaque(true);

        ldbTime1.setBackground(new java.awt.Color(0, 0, 0));
        ldbTime1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ldbTime1.setForeground(new java.awt.Color(255, 255, 255));
        ldbTime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ldbTime1.setText("10.30-1.30");
        ldbTime1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0), null, new java.awt.Color(153, 0, 0)));
        ldbTime1.setOpaque(true);
        ldbTime1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ldbTime1MouseClicked(evt);
            }
        });

        lblTime2.setBackground(new java.awt.Color(0, 0, 0));
        lblTime2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTime2.setForeground(new java.awt.Color(255, 255, 255));
        lblTime2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime2.setText("2.30-4.30");
        lblTime2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0), null, new java.awt.Color(153, 0, 0)));
        lblTime2.setOpaque(true);
        lblTime2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTime2MouseClicked(evt);
            }
        });

        lblTime3.setBackground(new java.awt.Color(0, 0, 0));
        lblTime3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTime3.setForeground(new java.awt.Color(255, 255, 255));
        lblTime3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime3.setText("6.30-8.30");
        lblTime3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0), null, new java.awt.Color(153, 0, 0)));
        lblTime3.setOpaque(true);
        lblTime3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTime3MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Disney_Movies__100px.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/movieticketreservation/img/icons8_Movie_Projector_100px_2.png"))); // NOI18N

        lblAllCustomer.setBackground(new java.awt.Color(0, 153, 0,110));
        lblAllCustomer.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblAllCustomer.setForeground(new java.awt.Color(0, 51, 51));
        lblAllCustomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAllCustomer.setOpaque(true);

        allPaymrent1.setBackground(new java.awt.Color(0, 0, 204,110));
        allPaymrent1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        allPaymrent1.setForeground(new java.awt.Color(0, 51, 51));
        allPaymrent1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        allPaymrent1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Total Incom");

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText(" Reservation");

        javax.swing.GroupLayout pnlRemoveLayout = new javax.swing.GroupLayout(pnlRemove);
        pnlRemove.setLayout(pnlRemoveLayout);
        pnlRemoveLayout.setHorizontalGroup(
            pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRemoveLayout.createSequentialGroup()
                .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRemoveLayout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRemoveLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel5))
                            .addComponent(jLabel7)))
                    .addGroup(pnlRemoveLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRemoveLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(ldbTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblTime3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRemoveLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRemoveLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRemoveLayout.createSequentialGroup()
                                .addComponent(allPaymrent1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(lblAllCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRemoveLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(576, 576, 576))
        );
        pnlRemoveLayout.setVerticalGroup(
            pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRemoveLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRemoveLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addComponent(jLabel6)
                .addGap(44, 44, 44)
                .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ldbTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTime3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRemoveLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblAllCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRemoveLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(allPaymrent1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRemove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ldbTime1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ldbTime1MouseClicked
        try {
            setColors();
            ldbTime1.setBackground(Color.red);
            DefaultTableModel dtm = (DefaultTableModel) tableMovie.getModel();
            dtm.setRowCount(0);
            SheduleDTO shedule = ManageShaduleController.searchByTime(ldbTime1.getText());
            MovieDTO movie = ManageMovieController.search(shedule.getMovieID());
            CategortDTO categort = ManageCategoryController.SerchCategory(movie.getCategoryId());
            Object[] rowdata = {shedule.getTime(), shedule.getMovieID(), movie.getMoveName(), categort.getCategoryName(), movie.getStartDate(), movie.getEndDate()
            };
            dtm.addRow(rowdata);

        } catch (Exception ex) {
            Logger.getLogger(ShowMoving.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ldbTime1MouseClicked

    private void lblTime2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTime2MouseClicked
        try {
            setColors();
            lblTime2.setBackground(Color.red);
            DefaultTableModel dtm = (DefaultTableModel) tableMovie.getModel();
            dtm.setRowCount(0);
            SheduleDTO shedule = ManageShaduleController.searchByTime(lblTime2.getText());

            MovieDTO movie = ManageMovieController.search(shedule.getMovieID());
            CategortDTO categort = ManageCategoryController.SerchCategory(movie.getCategoryId());
            Object[] rowdata = {shedule.getTime(), shedule.getMovieID(), movie.getMoveName(), categort.getCategoryName(), movie.getStartDate(), movie.getEndDate()
            };
            dtm.addRow(rowdata);
        } catch (Exception ex) {
            Logger.getLogger(ShowMoving.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblTime2MouseClicked

    private void lblTime3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTime3MouseClicked
        try {
            setColors();
            lblTime3.setBackground(Color.red);
            DefaultTableModel dtm = (DefaultTableModel) tableMovie.getModel();
            dtm.setRowCount(0);
            SheduleDTO shedule = ManageShaduleController.searchByTime(lblTime3.getText());

            MovieDTO movie = ManageMovieController.search(shedule.getMovieID());
            CategortDTO categort = ManageCategoryController.SerchCategory(movie.getCategoryId());
            Object[] rowdata = {shedule.getTime(), shedule.getMovieID(), movie.getMoveName(), categort.getCategoryName(), movie.getStartDate(), movie.getEndDate()
            };
            dtm.addRow(rowdata);
        } catch (Exception ex) {
            Logger.getLogger(ShowMoving.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblTime3MouseClicked

    private void tableMovieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMovieMouseClicked
       
        DefaultTableModel dtm = (DefaultTableModel) tableMovie.getModel();
        String mid = (String) dtm.getValueAt(0, 1);
        String name = (String) dtm.getValueAt(0, 2);
        BookingSeet booking = new BookingSeet(mid, name);
        pnlDetails.setVisible(false);
        pnlRemove.removeAll();
        booking.setSize(pnlRemove.getSize());
        pnlRemove.add(booking);
        pnlRemove.revalidate();
        pnlRemove.repaint();
    }//GEN-LAST:event_tableMovieMouseClicked
    private void setColors() {
        ldbTime1.setBackground(Color.black);
        lblTime2.setBackground(Color.black);
        lblTime3.setBackground(Color.black);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allPaymrent1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAllCustomer;
    private javax.swing.JLabel lblTime2;
    private javax.swing.JLabel lblTime3;
    private javax.swing.JLabel ldbTime1;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPanel pnlRemove;
    private javax.swing.JTable tableMovie;
    // End of variables declaration//GEN-END:variables

    private void loodAllpayment() {
        try {
            ArrayList<PaymentDTO> allPayment = ManagePaymentController.getSumofPayment();
            for (PaymentDTO payment : allPayment) {
                double[] rowdata = {payment.getAmount()
                };
                allPaymrent1.setText("" + payment.getAmount());
            }
        } catch (Exception ex) {
            Logger.getLogger(ShowMoving.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loodAlCustomerCount() {
        try {
            int count = ManageCustomerController.getSumOfCustomer();
            lblAllCustomer.setText("" + count);
        } catch (Exception ex) {
            Logger.getLogger(ShowMoving.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
